### ISSUE TITLE
ModuleNotFoundError: No module named 'jsonrpcclient.clients'

### ISSUE THREAD

**Issue by Max0nyM** [MrNaif2018/bitcart-sdk#6] opened 2019-10-13 02:43 UTC
ModuleNotFoundError: No module named 'jsonrpcclient.clients', jsonrpcclient is installed, what can i do? Thanks

**Comment by Max0nyM** [comment] 2019-10-13 02:57
jsonrpcclient.exceptions.ReceivedErrorResponseError: Invalid parameters: addrequest() got an unexpected keyword argument 'xpub' 

now getting this error :) should i install bitcart first and then sdk?

**Comment by MrNaif2018** [comment] 2019-10-13 06:33
I was doing bug fixes yesterday, you should update your bitcart daemon(run git pull in your cloned bitcart repo, and then pip install -U -r requirements/daemons/btc.txt). And also update SDK if there is any new version. About no module clients, how did you install the SDK? Sync version should install jsonrpclib[requests], and async should install jsonrpclib[aiohttp].

**Comment by Max0nyM** [comment] 2019-10-13 12:34
Just wanna ask if i can use sdk without bitcart, as RPC user pass i will set electrum rpc user password

**Comment by MrNaif2018** [comment] 2019-10-13 12:54
Bitcart SDK is just a wrapper around bitcart daemon.
Default settings in SDK should work with default settings in daemon.
So you need to connect to some daemon.
It was done to don't mess all the working with electrum code client side, and to allow accessing from other languages.

**Comment by Max0nyM** [comment] 2019-10-13 13:02
Connected to electrum daemon then tried to create request and got this
raise ValueError("Error from server: {}".format(e.response.message))
ValueError: Error from server: Invalid parameters: addrequest() got an unexpected keyword argument 'xpub'

**Comment by MrNaif2018** [comment] 2019-10-13 13:05
Electrum daemon? Or bitcart daemon?
Did you run the daemon with` python3 daemons/btc.py` from within cloned bitcart repo?
Try updating your cloned repo via `git pull`

**Comment by MrNaif2018** [comment] 2019-10-15 14:30
Did it help you? Or the issue persists?

**Comment by MrNaif2018** [comment] 2019-10-26 18:20
Closing this @Max0nyM, if you still have issues please reopen it. I am unable to reproduce it.

**Closed by MrNaif2018** 2019-10-26 18:20 UTC
